edition = "2021"
force_explicit_abi = true
group_imports = "StdExternalCrate"
hard_tabs = false
imports_granularity = "Crate"
imports_layout = "Vertical"
max_width = 100
merge_derives = true
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
unstable_features = true
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
