[package]
name = "telegram_bot_template_rust"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.64"
chrono = "0.4.22"
env_logger = "0.9.0"
getopts = "0.2.21"
log = "0.4.17"
regex = { version = "1.6.0", default-features = false, features = ["std", "unicode-perl"] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_derive = "1.0.144"
serde_json = "1.0.85"
signal-hook = "0.3.14"
teloxide = { version = "0.10.1", features = ["macros", "auto-send"] }
thiserror = "1.0.34"
tokio = { version = "1.21.0", features = ["rt-multi-thread", "macros", "sync"] }
toml = "0.5.9"
url = "2.2.2"
reqwest = { version = "0.11.11", features = ["json"] }
openssl = { version = "0.10.41", features = ["vendored"], optional = true }
