[package]
name = "telegram_bot_template_rust"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
env_logger = "0.10.0"
getopts = "0.2.21"
log = "0.4.18"
regex = { version = "1.8.3", default-features = false, features = ["std", "unicode-perl"] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_derive = "1.0.163"
serde_json = "1.0.96"
signal-hook = "0.3.15"
teloxide = { version = "0.12.2", features = ["macros", "auto-send"] }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros", "sync", "fs"] }
toml = "0.7.4"
url = "2.3.1"
reqwest = { version = "0.11.18", features = ["json"] }
openssl = { version = "0.10.54", features = ["vendored"], optional = true }
